This notebook contains all essential NumPy functions discussed on Intro to Data Science section.
For more detailed tutorial, visit note.nkmk.me.

Have fun!

In [94]:
import numpy as np

# Arrays

#### Create array

Create array

In [95]:
arr1D = np.array([1,2,3])
# [1 2 3]
print(f"Our 1-Dimensional array: \n {arr1D}")

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
#  [[1 2 3]
#   [4 5 6]]
print(f"Our 2-Dimensional array: \n {arr2D}")

Our 1-Dimensional array: 
 [1 2 3]
Our 2-Dimensional array: 
 [[1 2 3]
 [4 5 6]]


Creating array with same values.

In [96]:
zeroMatrix = np.zeros((2,3),dtype=int)
# [[0 0 0]
#  [0 0 0]]
print(f"Matrix with zero values: \n {zeroMatrix}")

Matrix with zero values: 
 [[0 0 0]
 [0 0 0]]


In [97]:
onesMatrix = np.ones((2, 3), dtype=int)
# [[1 1 1]
#  [1 1 1]]
print(f"Matrix with ones: \n {onesMatrix}")

Matrix with ones: 
 [[1 1 1]
 [1 1 1]]


In [98]:
fullMatrix = np.full((2,3), 0.5)
# [[0.5 0.5 0.5]
#  [0.5 0.5 0.5]]
print(f"Matrix with given number: \n {fullMatrix}")

Matrix with given number: 
 [[0.5 0.5 0.5]
 [0.5 0.5 0.5]]


To create an array filled with 0 or 1 that has the same shape and data type as another array can use np.zeros_like()
or ones_like().

#### Check dimension
You can get the number of dimensions of a NumPy array

In [99]:
numberOfDimensions1Darray = arr1D.ndim
# 1
print(f"Dimension of our first array: {numberOfDimensions1Darray}")

numberOfDimensions2Darray = arr2D.ndim
# 2
print(f"And out second array: {arr2D.ndim}")

Dimension of our first array: 1
And out second array: 2


#### Check shape
You can get the shape, i.e., the length of each dimension

In [100]:
shapeOf1Darr = arr1D.shape
# (3,)
print(f"Shape of our first array: {shapeOf1Darr}")

shapeOf2Darr = arr2D.shape
# (3,2)
print(f"Shape of our second array: {shapeOf2Darr}")

Shape of our first array: (3,)
Shape of our second array: (2, 3)


We can reshape array

In [101]:
reshapedArr = arr2D.reshape(6,)
# [1 2 3 4 5 6]
print(f"Reshaped array: {reshapedArr}")

Reshaped array: [1 2 3 4 5 6]


We can also unpack the returned tuple

In [102]:
row, col = arr2D.shape
print(f"Number of rows (first number in tuple): {row}")
print(f"Number of columns (second number in tuple): {col}")

Number of rows (first number in tuple): 2
Number of columns (second number in tuple): 3


#### Accesing array elements

In [103]:
firstRowOf2Darr = arr2D[0]
# [1 2 3]
print(f"Access first row: {firstRowOf2Darr}")

firstElementOf2Darr = arr2D[0][0]
# 1
print(f"Access element at index [0][0]: {firstElementOf2Darr}")

Access first row: [1 2 3]
Access element at index [0][0]: 1


#### Array element types
We can check data type of array

In [104]:
typeOfArr = arr1D.dtype
# int64
print(f"Data type of array: {typeOfArr}")

Data type of array: int64


We can specify data type

In [105]:
arrayWithFloats = np.array([1,2,3], dtype=float)
# float64
print(f"Data type of array: {arrayWithFloats.dtype}")

Data type of array: float64


We can change type

In [106]:
newDataTypeArr = arrayWithFloats.astype(int)
# int64
print(f"Data type of array: {newDataTypeArr.dtype}")

Data type of array: int64


#### Generate array
With arange, we specify interval.

np.arange(stop)

    0 <= n < stop with an interval of 1


np.arange(start, stop)

    start <= n < stop with an interval of 1


np.arange(start, stop, step)

    start <= n < stop with an interval of step

In [107]:
start = 1
stop = 5
step = 1

arr = np.arange(start, stop, step)
# 1 2 3 4
print(f"Generated array: {arr}")

Generated array: [1 2 3 4]


With linespace, we specify number of elements.

In [108]:
start = 1
stop = 10
numberOfElements = 5

arr = np.linspace(start, stop, numberOfElements)
#
print(f"Generated array: {arr}")

Generated array: [ 1.    3.25  5.5   7.75 10.  ]


We can generate random values. It is handy while prototyping. Here is basic random array implementation.

In [109]:
seed = 1234                             # We can specify seed for pseudorandom algorithm
rng = np.random.default_rng(seed)       # We create Generator instance
randomVal = rng.random((2, 3))          # Create 2x3 matrix with random values
#[[0.97669977 0.38019574 0.92324623]
# [0.26169242 0.31909706 0.11809123]]
print(f"Random value: \n {randomVal}")

Random value: 
 [[0.97669977 0.38019574 0.92324623]
 [0.26169242 0.31909706 0.11809123]]


More: https://note.nkmk.me/en/python-numpy-random/

#### Manipulate arrays

We can replace elements of NumPy array that satisfy given conditions.

In [110]:
manipulatedArr = np.where(arr2D < 4,0,1)
# [[0 0 0]
#  [1 1 1]]
print(f"Manipulated array, where we change numbers less than 4 to 0 and to 1 otherwise:\n {manipulatedArr}")

Manipulated array, where we change numbers less than 4 to 0 and to 1 otherwise:
 [[0 0 0]
 [1 1 1]]


Multiple conditions are possible by enclosing each condition in () and using & or |.

Transpose array (matrix). Often used in ML algorithms where parameters are stored in vectors.

In [133]:
print(f"Our base matrix: \n {arr2D}")

arrTransposed = arr2D.T
# [[1 4]
#  [2 5]
#  [3 6]]
print(f"Transposed matrix: \n {arrTransposed}")

Our base matrix: 
 [[1 2 3]
 [4 5 6]]
Transposed matrix: 
 [[1 4]
 [2 5]
 [3 6]]


#### Built in functions

np.sum()

axis=0 sum for each column

axis=1 sum for each row

Read more about axis: https://note.nkmk.me/en/python-numpy-axis-keepdims/

In [111]:
print(f"Remind how base matrix looks like: \n {arr2D} \n")

sumOfColumns = np.sum(arr2D, axis=0)
# [5 7 9]
print(f"Summed columns: {sumOfColumns}")

sumOfRows= np.sum(arr2D, axis=1)
# [6 15]
print(f"Summed columns: {sumOfRows}")

sumEntireArr = np.sum(arr2D)
# 21
print(f"Summed entire matrix: {sumEntireArr}")

Remind how base matrix looks like: 
 [[1 2 3]
 [4 5 6]] 

Summed columns: [5 7 9]
Summed columns: [ 6 15]
Summed entire matrix: 21


np.mean()

Specifying the axis argument changes this behavior to return the maximum and minimum values for each column or row.

In [112]:
meanOfColumns = np.mean(arr2D, axis=0)
# [2.5 3.5 4.5]
print(f"Mean of columns: {meanOfColumns}")

meanOfRows = np.mean(arr2D, axis=1)
# [2.5 3.5 4.5]
print(f"Mean of columns: {meanOfRows}")

meanOfEntireArr = np.mean(arr2D)
# [2.5 3.5 4.5]
print(f"Mean from entire matrix: {meanOfEntireArr}")

Mean of columns: [2.5 3.5 4.5]
Mean of columns: [2. 5.]
Mean from entire matrix: 3.5


np.max() and np.min()

Specifying the axis argument changes this behavior to return the maximum and minimum values for each column or row.

In [118]:
maxOfEachColumn = np.max(arr2D, axis=0)
# [4 5 6]
print(f"Max of each column: {maxOfEachColumn}")

maxOfEachRow = np.max(arr2D, axis=1)
# [3 6]
print(f"Max of each row: {maxOfEachRow}")

maxOfEntireArr = np.max(arr2D)
# 6
print(f"Max of entire array: {maxOfEntireArr}")

Max of each column: [4 5 6]
Max of each row: [3 6]
Max of entire array: 6


Standard deviation: np.std()

Variance: np.var()

Specifying the axis argument changes this behavior to return the maximum and minimum values for each column or row.

In [121]:
stdOfEachColumn = np.std(arr2D, axis=0)
# [1.5 1.5 1.5]
print(f"Std of each column: {stdOfEachColumn}")

stdOfEachRow = np.std(arr2D, axis=1)
# [0.81649658 0.81649658]
print(f"Std of each row: {stdOfEachRow}")

stdOfEntireArr = np.std(arr2D)
# 1.707825127659933
print(f"Std of entire arr: {stdOfEntireArr}")

Std of each column: [1.5 1.5 1.5]
Std of each row: [0.81649658 0.81649658]
Std of entire arr: 1.707825127659933


In [123]:
varOfEachColumn = np.var(arr2D, axis=0)
# [2.25 2.25 2.25]
print(f"Variance of each column: {varOfEachColumn}")

varOfEachRow = np.var(arr2D, axis=1)
# [0.66666667 0.66666667]
print(f"Variance of each row: {varOfEachRow}")

varOfEntireArr = np.var(arr2D)
# 2.9166666666666665
print(f"Variance of entire arr: {varOfEntireArr}")

Variance of each column: [2.25 2.25 2.25]
Variance of each row: [0.66666667 0.66666667]
Variance of entire arr: 2.9166666666666665


Round values: np.floor(), np.trunc(), np.ceil()

In [130]:
arrToBeRounded = np.array([[10.0, 10.1, 10.9], [-10.0, -10.1, -10.9]])

roundFloor = np.floor(arrToBeRounded) # Rounded down
# [[ 10.  10.  10.]
#  [-10. -11. -11.]]
print(f"Array with values rounded down: \n {roundFloor}")

roundTrunc = np.trunc(arrToBeRounded) # Rounded towards zero
# [[ 10.  10.  10.]
#  [-10. -10. -10.]]
print(f"Array with truncated values: \n {roundTrunc}")

roundCeil = np.ceil(arrToBeRounded)   # Rounded up
# [[ 10.  11.  11.]
#  [-10. -10. -10.]]
print(f"Array with values rounded up: \n {roundCeil}")


Array with values rounded down: 
 [[ 10.  10.  10.]
 [-10. -11. -11.]]
Array with truncated values: 
 [[ 10.  10.  10.]
 [-10. -10. -10.]]
Array with values rounded up: 
 [[ 10.  11.  11.]
 [-10. -10. -10.]]


Find the unique elements of an array.

In [139]:
uniqueArr = np.unique(roundTrunc) # We used truncated array
# [-10. 10.]
print(f"Arr with unique, sorted values: {uniqueArr}")

Arr with unique, sorted values: [-10.  10.]


# Use of NumPy in practice